#include "si/TouchstoneWriter.h"

#include <cstddef>
#include <format>
#include <fstream>
#include <sstream>

namespace sikit::touchstone {

std::string TouchstoneWriter::to_string(const TouchstoneFile& f) {
    if (f.num_ports < 1) {
        throw TouchstoneParseError("write: num_ports must be >= 1");
    }
    if (f.frequencies.size() != f.s_matrices.size()) {
        throw TouchstoneParseError(std::format(
            "write: frequencies ({}) and s_matrices ({}) length mismatch",
            f.frequencies.size(), f.s_matrices.size()));
    }
    const std::size_t expected = static_cast<std::size_t>(f.num_ports) *
                                  static_cast<std::size_t>(f.num_ports);
    for (std::size_t k = 0; k < f.s_matrices.size(); ++k) {
        if (f.s_matrices[k].size() != expected) {
            throw TouchstoneParseError(std::format(
                "write: s_matrices[{}] has {} entries, expected {}",
                k, f.s_matrices[k].size(), expected));
        }
    }

    std::ostringstream os;
    if (f.version == 2) {
        // ----- Touchstone v2 emission ------------------------------
        // Layout matches the v2 spec example: comment, [Version], the
        // legacy # option line, [Number of Ports], optional
        // [Two-Port Order], optional [Reference], [Network Data]
        // block, then [End]. The numeric body itself is the same
        // floats-per-record format as v1.
        os << "! Generated by sikit (Touchstone v2)\n";
        os << "[Version] 2.0\n";
        // 2-port v2 conventionally uses 12_21 (row-major); preserve the
        // file's declared ordering instead so a round-trip is exact.
        os << "# Hz S RI R " << f.reference_impedance << "\n";
        os << "[Number of Ports] " << f.num_ports << "\n";
        if (f.num_ports == 2) {
            os << "[Two-Port Order] "
               << (f.two_port_order == TwoPortOrder::RowMajor ? "12_21" : "21_12")
               << "\n";
        }
        if (!f.port_impedances.empty()) {
            os << "[Reference]";
            for (double z : f.port_impedances) {
                os << " " << z;
            }
            os << "\n";
        }
        os << "[Network Data]\n";

        const int N = f.num_ports;
        for (std::size_t k = 0; k < f.frequencies.size(); ++k) {
            os << std::format("{:.9e}", f.frequencies[k]);
            if (N == 2 && f.two_port_order == TwoPortOrder::LegacyColumnMajor) {
                // legacy: S11 S21 S12 S22 (storage order)
                for (std::size_t i = 0; i < 4; ++i) {
                    const auto& z = f.s_matrices[k][i];
                    os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
                }
            } else if (N == 2) {
                // row-major: S11 S12 S21 S22 (swap idx 1 and 2)
                const auto& m = f.s_matrices[k];
                const std::complex<double> ordered[4] = {m[0], m[2], m[1], m[3]};
                for (const auto& z : ordered) {
                    os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
                }
            } else {
                for (int r = 0; r < N; ++r) {
                    for (int c = 0; c < N; ++c) {
                        const auto& z = f.s_matrices[k][r + c * N];
                        os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
                    }
                    if (r + 1 < N) os << "\n  ";
                }
            }
            os << "\n";
        }
        os << "[End]\n";
        return os.str();
    }

    os << "! Generated by sikit\n";
    os << "! ports=" << f.num_ports << "  Zref=" << f.reference_impedance << " Ohm\n";
    // Always emit in RI form with Hz units -- universally accepted.
    os << "# Hz S RI R " << f.reference_impedance << "\n";

    const int N = f.num_ports;
    for (std::size_t k = 0; k < f.frequencies.size(); ++k) {
        os << std::format("{:.9e}", f.frequencies[k]);

        if (N == 2) {
            // Historical Touchstone 2-port order: S11 S21 S12 S22.
            // Storage is column-major: [S11, S21, S12, S22] at indices 0..3.
            for (std::size_t i = 0; i < 4; ++i) {
                const auto& z = f.s_matrices[k][i];
                os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
            }
        } else {
            // N != 2: row-major in the file. Storage is column-major
            // ([r + c*N]), so we re-iterate by file order (r outer, c inner).
            for (int r = 0; r < N; ++r) {
                for (int c = 0; c < N; ++c) {
                    const auto& z = f.s_matrices[k][r + c * N];
                    os << std::format("  {:.9e} {:.9e}", z.real(), z.imag());
                }
                if (r + 1 < N) os << "\n  ";  // line-wrap rows
            }
        }
        os << "\n";
    }
    return os.str();
}

void TouchstoneWriter::write_file(const TouchstoneFile& f,
                                   const std::filesystem::path& path) {
    std::ofstream out(path);
    if (!out) {
        throw TouchstoneParseError(std::format(
            "write: cannot open file: {}", path.string()));
    }
    out << to_string(f);
}

}  // namespace sikit::touchstone
